services:
    hmac_annotation_driver:
        class: AW\HmacBundle\Annotations\Driver\AnnotationDriver
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
        arguments: [@annotation_reader, "@doctrine.orm.entity_manager", "%aw_hmac.hmac%"]
    AW_apiuser_service:
        class: AW\HmacBundle\Services\ApiUserService
        arguments: ["@doctrine.orm.default_entity_manager", "%aw_hmac.hmac_roles%"]